/**
 * @description       : A class to manage custom exception. Created as an effort to validate input data to invocable.
 *                      Can most probably be used in other places for the integration as well but isn't implemented that way as of now.
 * @author            : Malin Nilsson (Stretch Customer AB)
 * @group             :
 * @last modified on  : 2024-02-19
 * @last modified by  : Malin Nilsson (Stretch Customer AB)
 **/
public without sharing class BillectaException extends Exception {
}